name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"  # 安定版に合わせてOK。あなたのローカルに近い版でも可。

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Ensure base placeholder
        run: |
          if ! grep -q 'FLUTTER_BASE_HREF' web/index.html; then
            sed -i 's#</head>#  <base href="$FLUTTER_BASE_HREF">\n</head>#' web/index.html
          fi

      - name: Build Web (Pages path)
        run: flutter build web --base-href "/kaigishi_reset/" --pwa-strategy=none

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
